import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import AuthModalClient from "@/components/auth/AuthModalClient";
import IntlProviderClient from "@/components/providers/IntlProviderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }: any) {
  const locale = (params?.locale as string) ?? "en";
  // We intentionally load translations on the client to avoid server-side locale routing.
  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <IntlProviderClient>
          <ReactQueryProvider>
            <Layout>{children}</Layout>
            <AuthModalClient />
            <Toaster richColors position="top-center" />
          </ReactQueryProvider>
        </IntlProviderClient>
      </body>
    </html>
  );
}
