import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "@/i18n";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import InitReactI18nextClient from "@/i18n/InitReactI18nextClient";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import AuthModalClient from "@/components/auth/AuthModalClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InitReactI18nextClient />
        <ReactQueryProvider>
          <Layout>{children}</Layout>
          <AuthModalClient />
          <Toaster richColors position="top-center" />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
